### ISSUE TITLE
`scrape_redcap_repo` returns nothing

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_query_collection#14]
[`scrape_redcap_repo`](https://github.com/ctsit/redcap_query_collection/blob/1e82f3e629e7ffaf2bf93f147c3db8f70ef369f5/R/get_redcap_repo_data.R#L35) returns nothing but emptiness when called. This is probably due to an update to the structure of Vandy's [Repository of External Modules](https://redcap.vanderbilt.edu/consortium/modules/index.php). 

All this nothingness makes [`redcap_repo_report.Rmd`](https://github.com/ctsit/redcap_query_collection/blob/master/redcap_repo_report.Rmd) very dull, nay useless. :-( Could I get a fix  pronto? I need the result before COB today. By 3 p.m. would be best.

**Comment by michael-bentz** [comment]
Addressed by #15
