### ISSUE TITLE
Design a query to count active projects in past N days

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_query_collection#7]
Design a query to count active projects in past N days. See
https://community.projectredcap.org/questions/59411/production-projects-active-in-past-year.html for ideas on how to do this. 

The query will probably require a select on redcap_log_event. As this is a very large table, every effort should be made to included indexed fields that will reduce the query time. It would be great if the query will still performant on large redcap system when looking at 365 days of activity, but that might be an unrealistic goal.

**Comment by pbchase** [comment]
@tlstoffs, I'd certainly welcome your input on this.

**Comment by tlstoffs** [comment]
what are you considering "active" projects? someone had a logged event in the project?  

What's the N? Last 30 days?

**Comment by pbchase** [comment]
Logging an event is probably enough. The goal is to demonstrate the a customer is accessing the project. i.e., they used it and maybe even want it. It's all about us assessing the worth of the projects in our REDCap system. 

We might want to exclude redcap admins from the list of people who "want" a project. Our access in a customers project does not constitute interest by the customer.

**Comment by tlstoffs** [comment]
Yes, I would exclude the REDCap admins activity, although if I am building a project for them, and a user hasn't accessed it yet, I'd count that as being 'active' since they are paying me to build the project, hence they are interested, but IDK how difficult that would be to include.   I'd probably also exclude project deletion events done by users since that indicates non-interest.

**Comment by pbchase** [comment]
I'm not bothered that we might have trouble assessing interest in new projects. The end-users will use them soon enough. I am more interested in assessing interest in _older_ projects. 

I do appreciate your feedback on projects that have a pending deletion, though. Those are clearly _not_ of interest and should be excluded from the report.

**Comment by ljwoodley** [comment]
Must this be a `.sql`. I started writing in R but realized you may actually just want a `.sql`  file. @pbchase

**Comment by pbchase** [comment]
In this case, yes it has to be a .SQL. I know that sounds weird coming from me. :-)

If it's fast enough, my plan is to use it in https://github.com/ctsit/redcap_webservices which only knows how to use SQL.

**Comment by ljwoodley** [comment]
Addressed by PR #8
